https://youtu.be/Rbh1rieb3zc?si=XIMTveDC1y-U30HG

**numpy by code with harry**

In [70]:
#always use shift+enter

https://docs.scipy.org/doc/           
**useful website**

In [1]:
#above we use *** we can use ** for italic

In [2]:
import numpy as np

In [3]:
myarr=np.array([2,3,66,77])

In [4]:
myarr

array([ 2,  3, 66, 77])

In [5]:
myarr=np.array([2,3,66,77],np.int8)

In [6]:
myarr

array([ 2,  3, 66, 77], dtype=int8)

In [78]:
myarr[0]

2

In [79]:
myarr=np.array([[2,3,66,77]],np.int8)

In [80]:
#now it is a 2D array

In [81]:
myarr[0]

array([ 2,  3, 66, 77], dtype=int8)

In [82]:
myarr[0,1]

3

In [83]:
myarr.shape

(1, 4)

In [84]:
myarr.dtype

dtype('int8')

In [85]:
myarr[0,1] = 6

In [86]:
myarr

array([[ 2,  6, 66, 77]], dtype=int8)

**array creation: conversion from other python structures**

In [87]:
listarr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [88]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
listarr.dtype

dtype('int32')

In [90]:
listarr.shape

(3, 3)

In [91]:
listarr.size

9

In [92]:
np.array({22,33,33})

array({33, 22}, dtype=object)

In [93]:
#try to use dtype as float or int

In [94]:
zeros=np.zeros((2,5))

In [95]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [96]:
zeros.dtype

dtype('float64')

In [97]:
zeros.size

10

In [98]:
rng=np.arange(15)

In [99]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
lspace=np.linspace(2,50,10)

In [104]:
lspace

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

In [105]:
#it give array of 10 elements form 1 to 50 for equal spacing

In [106]:
#now we will create a random array using empty

In [109]:
emp=np.empty((4,6))

In [110]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86922637e-306, 6.23055991e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 1.60216183e-306,
        7.56602523e-307, 3.56043054e-307, 1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 6.23037317e-307,
        6.23053954e-307, 9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
        8.45590539e-307, 8.34445562e-308, 8.34402698e-308]])

In [111]:
emp_like=np.empty_like(lspace)

In [112]:
emp_like

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

In [113]:
#here is uses lspace and create an empty array of same size as lspace

In [114]:
ide=np.identity(12)

In [115]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [116]:
#it gives identity matrix of size 12

In [117]:
arr=np.arange(99)

In [118]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [119]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [120]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [121]:
arr=arr.reshape(3,33)

In [122]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [123]:
arr=arr.ravel()

In [124]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [125]:
arr.shape

(99,)

In [126]:
#for 1D we have 1 axis name as axis0
#for 2D we have 2 axis, axis0 and axix1......and so on

In [127]:
#33.34 mins in the vido

In [128]:
x=([[1,2,3],[4,5,6],[7,1,0]])

In [129]:
ar=np.array(x)

In [130]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [131]:
ar.sum(axis=0)

array([12,  8,  9])

In [132]:
#axis 0 is having arrow towards downward

In [133]:
#axis 1 is having arrow towards right

In [134]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [135]:
ar.T
#for transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [136]:
ar.flat

In [137]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [138]:
#how to use for loop in python???

In [139]:
ar.ndim
#dimentiom

2

In [140]:
ar.nbytes

36

In [141]:
#ar.xyz is attribute and ar.xyz() is a function

In [142]:
one=np.array([1,3,4,643,2])

In [143]:
one.argmax()

3

In [144]:
#argmax() it give the index of max element 

In [145]:
one.argmin()

0

In [146]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [147]:
#it give what should be index for the sorted array

In [148]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [149]:
ar.argmax()

6

In [150]:
ar.argmin()

8

In [151]:
#it straight the 2D array for giving index

In [152]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [153]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [154]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [155]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [157]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [158]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [159]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [160]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [161]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [162]:
#with we are able to do matix operations

In [163]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [164]:
[2,3]+[4,5]

[2, 3, 4, 5]

In [165]:
#see we can't do same  

In [166]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [167]:
ar.sum()

29

In [168]:
ar.max()

7

In [169]:
ar.min()

0

In [170]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [171]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [172]:
type(np.where(ar>5))

tuple

In [173]:
np.count_nonzero(ar)

8

In [174]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [175]:
#it has all the values except 2,2

In [176]:
ar[1,2]=0

In [177]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [178]:
import sys

In [180]:
py_ar=[0,4,55,2]
#python array

In [182]:
np_ar=np.array(py_ar)
#numpy array

In [183]:
sys.getsizeof(1)*len(py_ar)

112

In [185]:
np_ar.itemsize*np_ar.size

16

In [186]:
#see what a size difference!!!!!